import type { AppSettings, RoutingPolicy } from '@aido/types';
import { DEFAULT_SCORE_WEIGHTS } from '@aido/types';

/**
 * Task-type routing policies (§11, §27).
 *
 * These express *preferences*, not facts about any provider. A policy only ever
 * shapes scoring; the router still refuses to use a model without capability,
 * quota or a verified-enough cost story. `allowedQuotaTypes` deliberately
 * excludes `free_trial` by default — promotional credits are not a renewable
 * resource (§3).
 */
export const DEFAULT_ROUTING_POLICIES: RoutingPolicy[] = [
  {
    id: 'policy-architecture',
    name: 'Architecture & reasoning',
    taskType: 'architecture',
    preferCapabilities: ['reasoning', 'longContext', 'codeGeneration'],
    weightOverrides: { modelQuality: 1.6, capabilityMatch: 1.3, latency: 0.4 },
    qualityRequirement: 'maximum',
    maxLatencyMs: 120_000,
    maxCostUsd: 0,
    allowedQuotaTypes: ['free_renewable', 'user_hosted'],
    minContextWindow: 32_000,
    failoverDepth: 3,
    enabled: true,
    description: 'Maximum quality reasoning with large context; latency tolerated.',
  },
  {
    id: 'policy-planning',
    name: 'Planning & decomposition',
    taskType: 'planning',
    preferCapabilities: ['reasoning', 'structuredOutput'],
    weightOverrides: { modelQuality: 1.35, quotaAvailability: 1.3, latency: 0.6 },
    qualityRequirement: 'high',
    maxLatencyMs: 60_000,
    maxCostUsd: 0,
    allowedQuotaTypes: ['free_renewable', 'user_hosted'],
    minContextWindow: 16_000,
    failoverDepth: 3,
    enabled: true,
    description: 'Structured, reliable planning output; free quota preserved.',
  },
  {
    id: 'policy-code-generation',
    name: 'Code generation',
    taskType: 'code_generation',
    preferCapabilities: ['codeGeneration', 'structuredOutput', 'longContext'],
    weightOverrides: { capabilityMatch: 1.5, quotaAvailability: 1.2 },
    qualityRequirement: 'high',
    maxLatencyMs: 90_000,
    maxCostUsd: 0,
    allowedQuotaTypes: ['free_renewable', 'user_hosted'],
    minContextWindow: 32_000,
    failoverDepth: 4,
    enabled: true,
    description: 'Coding capability blended with quota awareness for high-volume writing.',
  },
  {
    id: 'policy-refactor',
    name: 'Simple refactors',
    taskType: 'refactor',
    preferCapabilities: ['codeGeneration'],
    weightOverrides: { latency: 1.6, quotaAvailability: 1.4, modelQuality: 0.7 },
    qualityRequirement: 'medium',
    maxLatencyMs: 30_000,
    maxCostUsd: 0,
    allowedQuotaTypes: ['free_renewable', 'user_hosted'],
    minContextWindow: 16_000,
    failoverDepth: 3,
    enabled: true,
    description: 'Fastest capable model; refactors are bounded and verifiable by tests.',
  },
  {
    id: 'policy-test-generation',
    name: 'Test generation',
    taskType: 'test_generation',
    preferCapabilities: ['codeGeneration', 'structuredOutput'],
    weightOverrides: { latency: 1.2, quotaAvailability: 1.5, modelQuality: 0.8 },
    qualityRequirement: 'medium',
    maxLatencyMs: 60_000,
    maxCostUsd: 0,
    allowedQuotaTypes: ['free_renewable', 'user_hosted'],
    minContextWindow: 16_000,
    failoverDepth: 4,
    enabled: true,
    description: 'High-volume, cheap generation; coverage matters more than elegance.',
  },
  {
    id: 'policy-security',
    name: 'Security audit',
    taskType: 'security_audit',
    preferCapabilities: ['reasoning', 'longContext'],
    weightOverrides: { modelQuality: 1.7, reliability: 1.3, latency: 0.3 },
    qualityRequirement: 'maximum',
    maxLatencyMs: 180_000,
    maxCostUsd: 0,
    allowedQuotaTypes: ['free_renewable', 'user_hosted'],
    minContextWindow: 32_000,
    failoverDepth: 3,
    enabled: true,
    description: 'Deep reasoning over full context; never trades accuracy for speed.',
  },
  {
    id: 'policy-review',
    name: 'Code review',
    taskType: 'code_review',
    preferCapabilities: ['codeGeneration', 'reasoning'],
    weightOverrides: { modelQuality: 1.4, taskCompatibility: 1.2 },
    qualityRequirement: 'high',
    maxLatencyMs: 90_000,
    maxCostUsd: 0,
    allowedQuotaTypes: ['free_renewable', 'user_hosted'],
    minContextWindow: 32_000,
    failoverDepth: 3,
    enabled: true,
    description: 'Review needs a different model than the author to be meaningful.',
  },
  {
    id: 'policy-documentation',
    name: 'Documentation',
    taskType: 'documentation',
    preferCapabilities: ['codeGeneration'],
    weightOverrides: { latency: 1.5, quotaAvailability: 1.6, modelQuality: 0.6 },
    qualityRequirement: 'medium',
    maxLatencyMs: 45_000,
    maxCostUsd: 0,
    allowedQuotaTypes: ['free_renewable', 'user_hosted'],
    minContextWindow: 16_000,
    failoverDepth: 4,
    enabled: true,
    description: 'Cheap/fast model; docs are low-risk and easily regenerated.',
  },
  {
    id: 'policy-summarization',
    name: 'Summarization & context compression',
    taskType: 'summarization',
    preferCapabilities: ['longContext'],
    weightOverrides: { latency: 1.8, quotaAvailability: 1.8, modelQuality: 0.5 },
    qualityRequirement: 'low',
    maxLatencyMs: 20_000,
    maxCostUsd: 0,
    allowedQuotaTypes: ['free_renewable', 'user_hosted'],
    minContextWindow: 32_000,
    failoverDepth: 4,
    enabled: true,
    description: 'Compression is our own cost-control mechanism: always use the cheapest model.',
  },
  {
    id: 'policy-database',
    name: 'Database design',
    taskType: 'database_design',
    preferCapabilities: ['reasoning', 'codeGeneration', 'structuredOutput'],
    weightOverrides: { modelQuality: 1.4, capabilityMatch: 1.2 },
    qualityRequirement: 'high',
    maxLatencyMs: 90_000,
    maxCostUsd: 0,
    allowedQuotaTypes: ['free_renewable', 'user_hosted'],
    minContextWindow: 32_000,
    failoverDepth: 3,
    enabled: true,
    description: 'Schema mistakes are expensive; favour quality with structured output.',
  },
  {
    id: 'policy-devops',
    name: 'DevOps & infrastructure',
    taskType: 'devops',
    preferCapabilities: ['codeGeneration', 'structuredOutput'],
    weightOverrides: { modelQuality: 1.2, reliability: 1.2 },
    qualityRequirement: 'high',
    maxLatencyMs: 90_000,
    maxCostUsd: 0,
    allowedQuotaTypes: ['free_renewable', 'user_hosted'],
    minContextWindow: 16_000,
    failoverDepth: 3,
    enabled: true,
    description: 'Infrastructure changes must be correct; prefer reliable models.',
  },
  {
    id: 'policy-performance',
    name: 'Performance analysis',
    taskType: 'performance_analysis',
    preferCapabilities: ['reasoning', 'codeGeneration'],
    weightOverrides: { modelQuality: 1.3, taskCompatibility: 1.2 },
    qualityRequirement: 'high',
    maxLatencyMs: 90_000,
    maxCostUsd: 0,
    allowedQuotaTypes: ['free_renewable', 'user_hosted'],
    minContextWindow: 32_000,
    failoverDepth: 3,
    enabled: true,
    description: 'Diagnosis quality drives the fix; moderate latency tolerance.',
  },
  {
    id: 'policy-research',
    name: 'Research',
    taskType: 'research',
    preferCapabilities: ['longContext', 'reasoning'],
    weightOverrides: { quotaAvailability: 1.4, modelQuality: 1.1 },
    qualityRequirement: 'high',
    maxLatencyMs: 120_000,
    maxCostUsd: 0,
    allowedQuotaTypes: ['free_renewable', 'user_hosted'],
    minContextWindow: 32_000,
    failoverDepth: 3,
    enabled: true,
    description: 'Broad synthesis; large context preferred, cost still bounded.',
  },
  {
    id: 'policy-general',
    name: 'General (catch-all)',
    taskType: '*',
    preferCapabilities: [],
    weightOverrides: {},
    qualityRequirement: 'medium',
    maxLatencyMs: 60_000,
    maxCostUsd: 0,
    allowedQuotaTypes: ['free_renewable', 'user_hosted'],
    minContextWindow: null,
    failoverDepth: 4,
    enabled: true,
    description: 'Used for anything without a dedicated policy.',
  },
];

export const DEFAULT_MAX_PARALLEL_AGENTS = 3;

export function defaultAppSettings(): AppSettings {
  return {
    theme: 'dark',
    denseMode: true,
    executionMode: 'supervised',
    freeOnlyMode: true,
    telemetryRetentionDays: 30,
    eventRetentionDays: 14,
    router: {
      weights: { ...DEFAULT_SCORE_WEIGHTS },
      freeOnlyMode: true,
      allowTrialCredits: false,
      spreadAcrossProviders: true,
      quotaReserveFloor: 0.05,
      blockUnknownPricing: true,
      policies: DEFAULT_ROUTING_POLICIES,
      learningEnabled: true,
    },
    sandbox: {
      workspaceRoot: '.workspaces',
      deniedPaths: [],
      commandTimeoutMs: 300_000,
      outputByteLimit: 512 * 1024,
      allowNetwork: true,
      allowedCommandPrefixes: [],
      approvalRequiredPrefixes: ['rm -rf', 'git push', 'git reset --hard', 'DROP TABLE', 'DROP DATABASE'],
    },
    quota: {
      reserveFraction: 0.05,
      reservationTtlMs: 120_000,
      defaultCooldownMs: 30_000,
      cooldownBackoffMultiplier: 2,
      maxCooldownMs: 30 * 60_000,
      learnFromHeaders: true,
      assumeUnknownIsUnlimited: true,
    },
    supervisor: {
      maxRetriesPerTask: 3,
      maxTokensPerTask: 400_000,
      maxTaskRuntimeMs: 20 * 60_000,
      maxAgentIterations: 12,
      maxParallelAgents: DEFAULT_MAX_PARALLEL_AGENTS,
      maxTotalRunTokens: null,
      failureCircuitBreaker: { failures: 5, windowMs: 10 * 60_000 },
      retryWithDifferentModel: true,
      loopDetectionWindow: 6,
      enabled: true,
    },
    security: {
      encryptCredentials: true,
      redactLogs: true,
      promptInjectionDefense: true,
      alwaysConfirmDestructive: true,
      secretFileGlobs: ['.env', '.env.*', '*.pem', '*.key', 'id_rsa', '.npmrc', '.netrc', 'credentials.json'],
      allowRepoContentToProviders: true,
    },
    notifications: { approvals: true, failures: true, quota: true, desktop: false },
  };
}
